{% set name = "mvt" %}
{% set version = "1.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mvt-{{ version }}.tar.gz
  sha256: 8141f98e522a8ac398c9f6e0aec5233d644b21a267eeeb378b6fe83f2c586dca

build:
  number: 1
  noarch: python
  entry_points:
    - mvt-ios = mvt.ios:cli
    - mvt-android = mvt.android:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - packaging >=21.0
    - requests >=2.26.0
  run:
    - adb-shell >=0.4.2
    - click >=8.0.3
    - iosbackup >=0.9.921
    - libusb1 >=2.0.1
    - packaging >=21.0
    - python >={{ python_min }}
    - requests >=2.26.0
    - rich >=10.12.0
    - simplejson >=3.17.5
    - tld >=0.12.6
    - tqdm >=4.62.3
    - appdirs >=1.4.4

test:
  imports:
    - mvt
    - mvt.android
  commands:
    - pip check
    - mvt-ios --help
    - mvt-android --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mvt-project/mvt
  summary: Mobile Verification Toolkit
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://docs.mvt.re/

extra:
  recipe-maintainers:
    - ickc
